<?php

namespace Tests\Feature;

use App\Clients\StockClientResponse;
use App\Models\Product;
use App\Models\Retailer;
use App\Models\User;
use App\Notifications\ImportantStockUpdate;
use Database\Seeders\ProductWithRetailer;
use Facades\App\Clients\ClientFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class TrackCommandTest extends TestCase
{
    use RefreshDatabase;

    public function __construct(?string $name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Notification::fake();
        $this->seed(ProductWithRetailer::class);
        $this->fakeClientResponse();

    }

    /**
     * @test
     */
    public function it_can_track_product_stock()
    {

        $this->assertFalse(Product::first()->inStock());
        $this->artisan("track");

        $this->assertTrue(Product::first()->inStock());

    }


}
